### PR TITLE
Fetch SCM URL from UC

### LINKED ISSUE #97: org.kohsuke.github.GHFileNotFoundException: https://api.github.com/repos/jenkinsci/commons-lang3-api
### Jenkins and plugins versions report

Plugins.txt taken from https://raw.githubusercontent.com/jenkins-docs/quickstart-tutorials/main/dockerfiles/plugins.txt

```
ant:497.v94e7d9fffa_b_9
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1169.va_f810c56e895
build-timeout:1.33
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.0
cloudbees-folder:6.928.v7c780211d66e
commons-lang3-api:3.14.0-76.vda_5591261cfe
commons-text-api:1.12.0-119.v73ef73f2345d
configuration-as-code:1810.v9b_c30a_249a_4c
credentials-binding:681.vf91669a_32e45
credentials:1371.vfee6b_095f0a_3
display-url-api:2.204.vf6fddd8a_8b_e9
durable-task:555.v6802fe0f0b_82
echarts-api:5.5.0-1
font-awesome-api:6.5.2-1
git-client:5.0.0
git:5.2.2
github-api:1.318-461.v7a_c09c9fa_d63
github-branch-source:1789.v5b_0c0cea_18c3
github:1.39.0
gradle:2.12
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jjwt-api:0.11.5-112.ve82dfb_224b_a_d
jquery3-api:3.7.1-2
junit:1265.v65b_14fa_f12f0
locale:519.v4e20f313cfa_f
mailer:472.vf7c289a_4b_420
matrix-auth:3.2.2
matrix-project:832.va_66e270d2946
metrics:4.2.21-451.vd51df8df52ec
mina-sshd-api-common:2.13.1-117.v2f1a_b_66ff91d
mina-sshd-api-core:2.13.1-117.v2f1a_b_66ff91d
okhttp-api:4.11.0-172.vda_da_1feeb_c6e
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-graph-view:313.v1322ce83d680
pipeline-groovy-lib:727.ve832a_9244dfa_
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2205.vc9522a_9d5711
pipeline-model-definition:2.2205.vc9522a_9d5711
pipeline-model-extensions:2.2205.vc9522a_9d5711
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2205.vc9522a_9d5711
pipeline-stage-view:2.34
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:4.1.0
resource-disposer:0.23
scm-api:690.vfc8b_54395023
script-security:1341.va_2819b_414686
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-credentials:337.v395d2403ccd4
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
structs:338.v848422169819
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
variant:60.v7290fc0eb_b_cd
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1316.v33eb_726c50b_a_
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3908.vd6b_b_5a_a_54010
workflow-durable-task-step:1360.v82d13453da_a_f
workflow-job:1400.v7fd111b_ec82f
workflow-multibranch:783.787.v50539468395f
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:920.v59f71ce16f04
ws-cleanup:0.46

```

### What Operating System are you using (both controller, and any agents involved in the problem)?

GitPod

### Reproduction steps

`java -jar plugin-modernizer-cli/target/jenkins-plugin-modernizer-999999-SNAPSHOT.jar --dry-run --plugin-file plugins.txt  --recipes AddPluginsBom,AddCodeOwner`

### Expected Results

No error. 🤷 

### Actual Results

It looks like the `-plugin` suffix may be lacking.

### Anything else?

_No response_

### Are you interested in contributing a fix?

_No response_

### PR DESCRIPTION
**Pull request by sridamul**
Initially, Repository name is used as in -p option
For EG: `42crunch-security-audit-plugin` (which is a repo name) instead of `42crunch-security-audit` (which is the plugin name)

Now, we can use the plugin short name instead of repo name.

### Testing done
Unit Tests

### Submitter checklist
- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Closes #97.

### CODE REVIEW

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java [hunk 1]
```diff
@@ -32,6 +32,8 @@ public class Settings {
 
     public static final String RECIPE_DATA_YAML_PATH = "recipe_data.yaml";
 
+    public static final String UPDATE_CENTER_URL = "https://updates.jenkins.io/current/update-center.actual.json";
```
Comment (gounthar) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java:35]: Shouldn't that URL be out of the code, in a properties file or something that would allow us to change it without rebuilding?

Comment (jonesbusy) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java]: Yea like the Plugin installation manager tool this must be configurable

File: plugin-modernizer-core/src/main/resources/update_center.properties [hunk 2]
```diff
@@ -0,0 +1 @@
+update.center.url=https://updates.jenkins.io/current/update-center.actual.json
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/resources/update_center.properties:1]: Is better than hard-coding but I would prefer same approach that the plugin installation manager (at least checking the presence of the environment variable `JENKINS_UC`

https://github.com/jenkinsci/plugin-installation-manager-tool 

```
--jenkins-update-center: (optional) Sets the main update center filename, which can also be set via the JENKINS_UC environment variable. If a CLI option is entered, it will override what is set in the environment variable. If not set via CLI option or environment variable, will default to https://updates.jenkins.io/update-center.actual.json
```

Comment (sridamul) [reply plugin-modernizer-core/src/main/resources/update_center.properties:1]: `--jenkins-update-center` is the option gets filename which is manually stored by user in local?

Comment (jonesbusy) [reply plugin-modernizer-core/src/main/resources/update_center.properties:1]: https://github.com/jenkinsci/plugin-installation-manager-tool/blob/f36aacd44012c75dd735930270229ee2fce884da/plugin-management-cli/src/main/java/io/jenkins/tools/pluginmanager/cli/CliOptions.java#L102

It's an URL

**Comment by sridamul** [comment]
Will take a look on review comments and merge conflicts tomorrow.

File: plugin-modernizer-core/src/main/resources/update_center.properties (hunk 2 above)
Comment (sridamul) [reply plugin-modernizer-core/src/main/resources/update_center.properties:1]: Added `JENKINS_UC` env in [cd7dfb3](https://github.com/jenkinsci/plugin-modernizer-tool/pull/87/commits/cd7dfb3f62f4907f63e8dc258885d009ab022463) will add new option (`--jenkins-update-center`) in next PR

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JenkinsPluginInfo.java [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+import io.jenkins.tools.pluginmodernizer.core.config.Settings;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+public class JenkinsPluginInfo {
+    private static final Logger LOG = LoggerFactory.getLogger(JenkinsPluginInfo.class);
+    private static final ObjectMapper objectMapper = new ObjectMapper();
+
+    @SuppressFBWarnings(value = "URLCONNECTION_SSRF_FD", justification = "safe url")
+    public static JsonNode getCachedJsonNode(Path cacheDir) throws IOException {
```
[the remark this answers is not in the document]
Comment (sridamul) [reply plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/utils/JenkinsPluginInfo.java:24]: > Also I'm not sure about returning a JsonNode which is an implementation detail for a public method

Maybe a custom data class to represent JSON data?

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java [hunk 4]
```diff
@@ -68,6 +71,14 @@ private static Path getDefaultMavenHome() {
         return readProperty("openrewrite.maven.plugin.version", "versions.properties");
     }
 
+    private static @Nullable String getUpdateCenterUrl() {
+        String url = System.getenv("JENKINS_UC");
+        if (url == null) {
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/config/Settings.java:76]: Good idea to have fallback on the property file

**Comment by sridamul** [comment]
Right now, removed the fn to create a cache dir from the `JenkinsPluginInfo` class. I am not sure where to put the fn. Any suggestions?

File: plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/UpdateCenterData.java [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+import com.fasterxml.jackson.databind.JsonNode;
+
+public class UpdateCenterData {
+    private final JsonNode jsonNode;
+
+    public UpdateCenterData(JsonNode jsonNode) {
+        this.jsonNode = Objects.requireNonNull(jsonNode, "jsonNode must not be null");
+    }
+
+    public JsonNode getPlugin(String pluginName) {
```
Comment (jonesbusy) [inline plugin-modernizer-core/src/main/java/io/jenkins/tools/pluginmodernizer/core/model/UpdateCenterData.java:16]: I think we really miss a Plugin class POJO (or record) to return such info

```java
public Plugin getPlugin(String pluginName) {
```

Would be more elegant that exposing implementation detail

For me this code can be cleanup in an other PR

**Review by jonesbusy — APPROVED** [review]
